### ISSUE TITLE
样例中的新手向导不能正常使用

### ISSUE THREAD

**Issue by cnwillz** [fairygui/FairyGUI-egret#22]
只有一个圈出现在按钮上,不能点击,无控制台报错

触发前:

![1](https://user-images.githubusercontent.com/9823932/97531876-1b8cf480-19f0-11eb-8a2c-2d570c295af7.png)

触发后:

![2](https://user-images.githubusercontent.com/9823932/97531882-1cbe2180-19f0-11eb-97e0-32efbbe00189.png)

**Comment by xiaoguzhu** [comment]
egret不支持挖洞，没有办法。用其他方式实现。

**Comment by cnwillz** [comment]
好的 感谢解惑
